### ISSUE TITLE
SNMP setings for Brother integration

### ISSUE THREAD

**Issue by Wolvverine** [bieniu/brother#119]
Printers, as well as other devices, have the option of both setting a different community name and using their own v3 configuration. Integration does not have the ability to configure its own SNMP settings.

**Comment by Wolvverine** [comment]
Bump...

**Comment by Taomyn** [comment]
Can we have this re-opened? SNMP v1/v2c are no longer deemed safe, so having v3 with full configuration is now necessary, thanks.
