### ISSUE TITLE
Toner type missing 

### ISSUE THREAD

**Issue by mikey0000** [bieniu/brother#169]
The options for printer type don't include toner.

Is toner able to be added?

**Comment by bieniu** [comment]
What do you mean by printer type toner?  Laser printers use toner.

**Comment by mikey0000** [comment]
Oh sorry I clearly didn't understand that. Like the business grade toner printers, are they technically a laser printer?

31/01/2023 8:45:44 am Maciej Bieniek ***@***.***>:

**Comment by bieniu** [comment]
I don't know what business grade toner printers are. Can you give me an example?

**Comment by mikey0000** [comment]
Don't worry I was unaware they all use lasers... so yeah even the business grade toner printers are laser. Sorry again.
