### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [bieniu/brother#18]
Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by bieniu** [comment]
Thanks for info.

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/brother/releases/tag/0.1.17

**Comment by fabaff** [comment]
Awesome, thanks
