### ISSUE TITLE
Default charset

### ISSUE THREAD

**Issue by tytytyty70** [bieniu/brother#97]
Would you please change the default character set from "roman8" to "utf8"?
Because Japanese models return utf8 text as a status code.

**Comment by bieniu** [comment]
Please paste some examples of statuses in Japanese here.

**Comment by tytytyty70** [comment]
Thank you for your reply.
With "roman8" charset, the status code is "ðƒððˆððêð°ð₤ð¤êì (bk)", but with "utf8", it is "まもなくインク交換 (bk)".
Thank you in advance for your consideration.

**Comment by bieniu** [comment]
Will be fixed.

**Comment by bieniu** [comment]
Could you show me response to this command:
```
snmpwalk -v1 -c public brother 1.3.6.1.2.1.43.7.1.1.4.1.1
```
